languageCode = "en"
languageName = "English"
weight = 1
title = "Intune - In Real Life"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "irl_logo.png"
description = "The Modern Device Whisperer: Making Tech Work for You"

[author]
name = "Somesh Pathak"
image = "img/blowfish_logo.png"
headline = "The Modern Device Whisperer: Making Tech Work for You"
bio = "A little bit about you"
