[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Tags"
pageRef = "tags"
weight = 30

[[main]]
name = "Home"
pageRef = "home"
identifier = "RBjl5IknbV"
weight = 9999

[[main]]
name = "About Me"
pageRef = "About Me"
identifier = "k3S8Tivw4i"
weight = 9999

[[main]]
name = "Contact Me"
pageRef = "newSite"
identifier = "5RqsHJgabJ"
weight = 9999

[[footer]]
none = "none"
